### ISSUE TITLE
Segment Duration over Time graph doesn't ignore skipped splits

### ISSUE THREAD

**Issue by glacials** [glacials/splits-io#527] opened 2019-03-19 22:20 UTC
When a split is skipped, the following split should not absorb its duration in the context of the Segment Duration over Time graph, but it seems that it is.

e.g. Bianco 3 and Bianco 7 on https://splits.io/3u5z

**Comment by moorecp** [comment] 2019-09-14 02:48
What's the intended behavior in this situation? In the case of Bianco 3, since Bianco 2 was skipped, you have no idea how much time should be attributed to Bianco 3. If you don't want the large spike, the only thing you can realistically do is just not display a data point for Bianco 3, as well.

This is also seen in #562, where it seems like the sensible thing to do is ignore splits following a skipped split from standard deviation calculations (but isn't quite that simple due to how it's calculated).

Any thoughts?

**Comment by glacials** [comment] 2019-09-14 05:54
Good question! I believe we should treat as missing data, because that's really what it is. A time might technically be present in Bianco 3's "slot", but really that number represents a third thing, the sum of Bianco 2 and Bianco 3, and that's not currently something that's useful to chart in any way.

We also shouldn't try to estimate what Bianco 3's time might have been based on previous/next segments, as that would be just plain lying and still subject to weird confusing spikes. Reporting it as null is the safest and best option.

Not sure if the chart will look better with connected nulls or not, but I believe in past similar situations we've decided to connect line charts across nulls.

**Comment by moorecp** [comment] 2019-09-14 16:51
I agree with leaving a hole in Bianco 3. The chart seems to look fine with it like that, but I feel like the fix for this can't go out without also fixing #562 since now the standard deviation is just completely bonkers since it's calculated using data not shown in the chart.

In testing a fix, I simply fixed it in the Javascript by filtering out the invalid data points, but this problem affects other parts of the app as seen with #562. Currently the data from the chart is coming from `RunBlueprint` -> `RunHistoryBlueprint`. The API request asks for all historic data. Does it make sense to change... something so only "valid" histories are returned? My guts says no and to see if it's possible to fix the query that's calculating standard deviation, but then the next question is, what about box plot? The Individual Segment Stats chart is already ignoring these specific situations (as I found out after I wrote basically the same code for SDOT). It just seems like there are multiple cases where the app doesn't want these types of data points, but does want them in other cases. It just seems bad to be applying the same fix multiple times.

**Comment by BatedUrGonnaDie** [comment] 2019-09-14 21:21
Could always just extract the logic that cleans up the histories to a separate file, and then include that where it's needed in the respective chart files.  Or have it be in the chart builder file itself so you have 1 copy of the original unfiltered run, and then you just pass in the filtered run to the charts that need it.

**Comment by glacials** [comment] 2019-09-15 05:50
Yeah I agree with your gut @moorecp; there should be a difference between "didn't finish this split" and "finished this split with an unknown time". fwiw in both JS and Ruby this should be a one-liner somewhere in the ballpark of `segments.filter(s => s !== null)` and `segments.compact` respectively.

If it ends up not being that simple, I agree with @BatedUrGonnaDie that we should extract it to a common function to be used by all the ways we display data, rather than compromise how we report the data. We do something similar in Rails with [`collapsed_segments`][1] to massage the data in the same way from multiple places.

[1]: https://github.com/glacials/splits-io/blob/e93d05a4541cad68223c94fd11bada61d0caf437/app/models/concerns/forgetful_persons_run.rb#L7-L41

**Closed** 2019-09-17 03:24 UTC
Labels: bug
