### ISSUE TITLE
Delete/Disown dropdown on authenticated homepage is not wide enough

### ISSUE THREAD

**Issue by jhobz** [glacials/splits-io#225] opened 2016-03-16 03:39 UTC
![image](https://cloud.githubusercontent.com/assets/1765799/13801305/187b5e98-eb07-11e5-95f8-ede6f859528d.png)

**Comment by glacials** [comment] 2016-03-16 03:42
Dupe of #214

**Closed by glacials** 2016-03-16 03:42 UTC
