### ISSUE TITLE
API not returning attempt count despite the page having the attempt count

### ISSUE THREAD

**Issue by MineRobber9000** [glacials/splits-io#257] opened 2016-11-14 23:35 UTC
[This is my run as described by the API](https://splits.io/api/v3/runs/xzw) and [this is the stats page from the normal website](https://splits.io/xzw/stats). One has the attempt count, the other does not.

**Comment by glacials** [comment] 2016-11-14 23:39
Can you paste the API endpoint's output that you see? For me both claim 5 attempts:

![screenshot 2016-11-14 15 38 18](https://cloud.githubusercontent.com/assets/438911/20287277/679e1c0c-aa80-11e6-93d9-5acf5c543a2a.png)

```bash
$ curl -s https://splits.io/api/v3/runs/xzw | json
```
```json
{
  "run": {
    "id": 44060,
    "path": "/xzw",
    "name": "Pokemon Black and Blue All Trainers",
    "program": "livesplit",
    "image_url": null,
    "created_at": "2016-11-14T23:12:10.174Z",
    "updated_at": "2016-11-14T23:33:30.771Z",
    "video_url": null,
    "splits": [
      {
        "name": "Cheren",
        "duration": "31.85",
        "finish_time": "31.85",
        "best": {
          "duration": "31.85"
        },
        "history": null,
        "gold": true,
        "skipped": false,
        "reduced": false
      },
      {
        "name": "Juniper",
        "duration": "90.44",
        "finish_time": "122.29",
        "best": {
          "duration": "70.84"
        },
        "history": null,
        "gold": false,
        "skipped": false,
        "reduced": false
      },
      {
        "name": "Ghetsis",
        "duration": "85.37",
        "finish_time": "207.66",
        "best": {
          "duration": "85.37"
        },
        "history": null,
        "gold": true,
        "skipped": false,
        "reduced": false
      },
      {
        "name": "Ash",
        "duration": "59.65",
        "finish_time": "267.31",
        "best": {
          "duration": "59.65"
        },
        "history": null,
        "gold": true,
        "skipped": false,
        "reduced": false
      }
    ],
    "attempts": 5,
    "sum_of_best": 247.715,
    "user": {
      "twitch_id": 45303424,
      "name": "minerobber___t",
      "avatar": "https://static-cdn.jtvnw.net/jtv_user_pictures/minerobber___t-profile_image-49160644935c8f4c-300x300.png",
      "created_at": "2016-11-14T23:11:27.162Z",
      "updated_at": "2016-11-14T23:11:27.162Z"
    },
    "game": {
      "id": 4397,
      "name": "Pokemon Black and Blue",
      "shortname": null,
      "created_at": "2016-11-14T23:12:11.079Z",
      "updated_at": "2016-11-14T23:12:11.079Z"
    },
    "category": {
      "id": 12930,
      "name": "All Trainers",
      "created_at": "2016-11-14T23:12:11.119Z",
      "updated_at": "2016-11-14T23:12:11.119Z"
    },
    "time": 267.311
  }
}
```

**Comment by MineRobber9000** [comment] 2016-11-14 23:44
Now it shows 5 attempts. Not sure what happened, but the "attempts" value said "null", like:

```json
"requests": null
```

**Comment by glacials** [comment] 2017-04-24 06:42
Closing since we couldn't reproduce.

**Closed by glacials** 2017-04-24 06:42 UTC
