### ISSUE TITLE
Website won't export splits unless on specific split page with "Route Only" unchecked.

### ISSUE THREAD

**Issue by ShimmerFairy** [glacials/splits-io#580] opened 2019-08-10 08:57 UTC
When trying to download a split from the website from a category page, or from a split's page with "Route Only" checked, the generic format option just gives a zero-byte JSON file. Other formats seem to at least have something inside, but no actual split data (all times are set to zero or are absent in these files). Sending the data to LiveSplit One just gets a "failed to download" error when the timer loads.

However, unchecking "Route Only" suddenly gives me an actual JSON file for the generic format, and actual timing data in the other formats. Sending to LiveSplit One still fails, however.

The .csv files seemingly give data in every situation, but I wouldn't know what a good one of those looks like.

I've tried to make it work on my end, but nothing's helped.

**Comment by glacials** [comment] 2019-08-11 15:27
Thanks for the report! I can reproduce and believe I've fixed in e64063aa2b95adbf251b7304a820a5f6bc7820d8. Can you check and confirm?

**Comment by ShimmerFairy** [comment] 2019-08-13 03:21
Downloading generic format splits works now. Where it was previously 0-byte files, I now get files giving the splits for the route without any specific run's times (which makes sense to me for "route only" files). The only thing still obviously broken is LiveSplit One exporting, but that could just as easily be a problem with that website.

**Comment by glacials** [comment] 2019-08-13 04:03
I cannot reproduce the broken LiveSplit One exporting, can you link me to a run that causes this? cc @CryZe @wooferzfg

**Comment by ShimmerFairy** [comment] 2019-08-13 05:55
That one's on me, I always forget that Privacy Badger can block scripts from loading. It works fine once I've allowed it to function.

**Comment by glacials** [comment] 2019-08-13 13:37
Ok! Closing then, thanks for bringing this up.

**Closed by glacials** 2019-08-13 13:37 UTC
Labels: bug
