### ISSUE TITLE
Game/category title not displayed on run page

### ISSUE THREAD

**Issue by jhobz** [glacials/splits-io#254] opened 2016-10-18 03:48 UTC
https://splits.io/w3d

The title/category are not displayed on the run page but are when I go to the stats page. Screenshot in case it shows up for you:

![image](https://cloud.githubusercontent.com/assets/1765799/19463683/1b585532-94c4-11e6-9b80-1f0bca7e66ad.png)

This persists through page refresh and happens in an incognito window.

Windows 7, Chrome Version 53.0.2785.143 m

**Comment by jhobz** [comment] 2016-10-18 03:51
To note, these splits use a custom component for the Ori autosplitter, so that may have something to do with it, although I doubt it because I think I've uploaded splits with that component before. Seems like a regression to me.

**Comment by glacials** [comment] 2016-10-18 05:20
This probably has something to do with the migration to DynamoDB for storing parsed runs, thanks I'll look into it!

**Comment by glacials** [comment] 2016-10-18 20:20
Hmm, somehow there's an issue with assigning a category to this (maybe other?) runs. We can parse it correctly and discover the game/category, and Rails _thinks_ it's correctly saving that info, but inevitably its `category_id` ends up `nil` in the database.

The title is built from `"#{game.name} #{category.name}"` so this is the cause of the "(no title)". The stats page shows the title correctly because that page does a full fetch of the original run from S3 and parses it completely (for the detailed history which powers the graphs), which sets game and category correctly on the local `@run` object in memory -- the changes are just never persisted to the database. Trying to figure out why. I think maybe there's a `before_save` callback on the loose somewhere.

**Comment by glacials** [comment] 2016-10-18 22:46
Okay this should be fixed (5e07379ca8184fcdf418661c9c20465d927b7e05). Some code I wrote recently to get rid of base 10 run IDs completely in favor of base 36 run IDs was not liked very well by Rails, which (I'm not sure why) started assuming that all run IDs were `0`, causing updates to look successful but actually be applied to the wrong row.

The fix was to keep base 10 IDs around and just use base 36 everywhere that matters except Rails internals.

**Closed by glacials** 2016-10-18 22:46 UTC
Labels: bug, parsing

**Comment by jhobz** [comment] 2016-10-18 22:48
Cool, I'll comment with confirmation once it has been deployed.

**Comment by jhobz** [comment] 2016-10-18 22:49
Nevermind, it clearly has been, I was just having a caching issue. LGTM!

**Comment by jhobz** [comment] 2016-10-18 22:50
It looks like https://splits.io/w3f wasn't claimed to my account though (w3d wasn't but that's because I wasn't logged in). Maybe claim tokens are broken?

**Comment by glacials** [comment] 2016-10-18 22:58
All DB updates to runs were broken, so if you uploaded this before the fix went out, yeah claim tokens would have been broken as well (since they update the run's user to be you). I've gone ahead and granted both those runs to you but let me know if this is actually still broken rn (I can't reproduce).

**Comment by jhobz** [comment] 2016-10-18 23:00
Ok great thanks, yeah they were both before this fix. I'll log a new issue if I see it happen again.
